// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package api

import (
	"net/http"
)

const (
	defaultBaseURI = "https://farshiverpeaks.com:8321/v1"
)

type GuildWars2VerificationAPI struct {
	client     http.Client
	AuthHeader string // Authorization header, will be sent on each request if not empty
	BaseURI    string
	common     service // Reuse a single struct instead of allocating one for each service on the heap.

	V1 *V1Service
}

type service struct {
	client *GuildWars2VerificationAPI
}

func NewGuildWars2VerificationAPI() *GuildWars2VerificationAPI {
	c := &GuildWars2VerificationAPI{
		BaseURI: defaultBaseURI,
		client:  http.Client{},
	}
	c.common.client = c

	c.V1 = (*V1Service)(&c.common)

	return c
}
